/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.poem;

import android.net.Uri;
import android.provider.BaseColumns;

import ca.rmen.android.palidamuerte.provider.PalidaMuerteProvider;

/**
 * Columns for the {@code poem} table.
 */
public interface PoemColumns extends BaseColumns {
    String TABLE_NAME = "poem";
    Uri CONTENT_URI = Uri.parse(PalidaMuerteProvider.CONTENT_URI_BASE + "/" + TABLE_NAME);

    String _ID = BaseColumns._ID;
    String POEM_TYPE_ID = "poem_type_id";
    String POEM_NUMBER = "poem_number";
    String SERIES_ID = "series_id";
    String CATEGORY_ID = "category_id";
    String LOCATION = "location";
    String YEAR = "year";
    String MONTH = "month";
    String DAY = "day";
    String TITLE = "title";
    String PRE_CONTENT = "pre_content";
    String CONTENT = "content";

    String DEFAULT_ORDER = _ID;

	// @formatter:off
    String[] FULL_PROJECTION = new String[] {
            _ID,
            POEM_TYPE_ID,
            POEM_NUMBER,
            SERIES_ID,
            CATEGORY_ID,
            LOCATION,
            YEAR,
            MONTH,
            DAY,
            TITLE,
            PRE_CONTENT,
            CONTENT
    };
    // @formatter:on
}