/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.poem_type;

import java.util.Date;

import android.database.Cursor;

import ca.rmen.android.palidamuerte.provider.base.AbstractCursor;

/**
 * Cursor wrapper for the {@code poem_type} table.
 */
public class PoemTypeCursor extends AbstractCursor {
    public PoemTypeCursor(Cursor cursor) {
        super(cursor);
    }

    /**
     * Get the {@code poem_type_name} value.
     * Cannot be {@code null}.
     */
    public String getPoemTypeName() {
        Integer index = getCachedColumnIndexOrThrow(PoemTypeColumns.POEM_TYPE_NAME);
        return getString(index);
    }
}
