/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.poem_type;

import android.net.Uri;
import android.provider.BaseColumns;

import ca.rmen.android.palidamuerte.provider.PalidaMuerteProvider;

/**
 * Columns for the {@code poem_type} table.
 */
public interface PoemTypeColumns extends BaseColumns {
    String TABLE_NAME = "poem_type";
    Uri CONTENT_URI = Uri.parse(PalidaMuerteProvider.CONTENT_URI_BASE + "/" + TABLE_NAME);

    String _ID = BaseColumns._ID;
    String POEM_TYPE_NAME = "poem_type_name";

    String DEFAULT_ORDER = _ID;

	// @formatter:off
    String[] FULL_PROJECTION = new String[] {
            _ID,
            POEM_TYPE_NAME
    };
    // @formatter:on
}