/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.poem_type;

import java.util.Date;

import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;

import ca.rmen.android.palidamuerte.provider.base.AbstractSelection;

/**
 * Selection for the {@code poem_type} table.
 */
public class PoemTypeSelection extends AbstractSelection<PoemTypeSelection> {
    @Override
    public Uri uri() {
        return PoemTypeColumns.CONTENT_URI;
    }

    /**
     * Query the given content resolver using this selection.
     *
     * @param contentResolver The content resolver to query.
     * @param projection A list of which columns to return. Passing null will return all columns, which is inefficient.
     * @param sortOrder How to order the rows, formatted as an SQL ORDER BY clause (excluding the ORDER BY itself). Passing null will use the default sort
     *            order, which may be unordered.
     * @return A {@code PoemTypeCursor} object, which is positioned before the first entry, or null.
     */
    public PoemTypeCursor query(ContentResolver contentResolver, String[] projection, String sortOrder) {
        Cursor cursor = contentResolver.query(uri(), projection, sel(), args(), sortOrder);
        if (cursor == null) return null;
        return new PoemTypeCursor(cursor);
    }

    /**
     * Equivalent of calling {@code query(contentResolver, projection, null}.
     */
    public PoemTypeCursor query(ContentResolver contentResolver, String[] projection) {
        return query(contentResolver, projection, null);
    }

    /**
     * Equivalent of calling {@code query(contentResolver, projection, null, null}.
     */
    public PoemTypeCursor query(ContentResolver contentResolver) {
        return query(contentResolver, null, null);
    }


    public PoemTypeSelection id(long... value) {
        addEquals(PoemTypeColumns._ID, toObjectArray(value));
        return this;
    }


    public PoemTypeSelection poemTypeName(String... value) {
        addEquals(PoemTypeColumns.POEM_TYPE_NAME, value);
        return this;
    }

    public PoemTypeSelection poemTypeNameNot(String... value) {
        addNotEquals(PoemTypeColumns.POEM_TYPE_NAME, value);
        return this;
    }

    public PoemTypeSelection poemTypeNameLike(String... value) {
        addLike(PoemTypeColumns.POEM_TYPE_NAME, value);
        return this;
    }
}
