/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.series;

import java.util.Date;

import android.content.ContentResolver;
import android.net.Uri;

import ca.rmen.android.palidamuerte.provider.base.AbstractContentValues;

/**
 * Content values wrapper for the {@code series} table.
 */
public class SeriesContentValues extends AbstractContentValues {
    @Override
    public Uri uri() {
        return SeriesColumns.CONTENT_URI;
    }

    /**
     * Update row(s) using the values stored by this object and the given selection.
     * 
     * @param contentResolver The content resolver to use.
     * @param where The selection to use (can be {@code null}).
     */
    public int update(ContentResolver contentResolver, SeriesSelection where) {
        return contentResolver.update(uri(), values(), where == null ? null : where.sel(), where == null ? null : where.args());
    }

    public SeriesContentValues putSeriesName(String value) {
        if (value == null) throw new IllegalArgumentException("value for seriesName must not be null");
        mContentValues.put(SeriesColumns.SERIES_NAME, value);
        return this;
    }


}
