/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.series;

import java.util.Date;

import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;

import ca.rmen.android.palidamuerte.provider.base.AbstractSelection;

/**
 * Selection for the {@code series} table.
 */
public class SeriesSelection extends AbstractSelection<SeriesSelection> {
    @Override
    public Uri uri() {
        return SeriesColumns.CONTENT_URI;
    }

    /**
     * Query the given content resolver using this selection.
     *
     * @param contentResolver The content resolver to query.
     * @param projection A list of which columns to return. Passing null will return all columns, which is inefficient.
     * @param sortOrder How to order the rows, formatted as an SQL ORDER BY clause (excluding the ORDER BY itself). Passing null will use the default sort
     *            order, which may be unordered.
     * @return A {@code SeriesCursor} object, which is positioned before the first entry, or null.
     */
    public SeriesCursor query(ContentResolver contentResolver, String[] projection, String sortOrder) {
        Cursor cursor = contentResolver.query(uri(), projection, sel(), args(), sortOrder);
        if (cursor == null) return null;
        return new SeriesCursor(cursor);
    }

    /**
     * Equivalent of calling {@code query(contentResolver, projection, null}.
     */
    public SeriesCursor query(ContentResolver contentResolver, String[] projection) {
        return query(contentResolver, projection, null);
    }

    /**
     * Equivalent of calling {@code query(contentResolver, projection, null, null}.
     */
    public SeriesCursor query(ContentResolver contentResolver) {
        return query(contentResolver, null, null);
    }


    public SeriesSelection id(long... value) {
        addEquals(SeriesColumns._ID, toObjectArray(value));
        return this;
    }


    public SeriesSelection seriesName(String... value) {
        addEquals(SeriesColumns.SERIES_NAME, value);
        return this;
    }

    public SeriesSelection seriesNameNot(String... value) {
        addNotEquals(SeriesColumns.SERIES_NAME, value);
        return this;
    }

    public SeriesSelection seriesNameLike(String... value) {
        addLike(SeriesColumns.SERIES_NAME, value);
        return this;
    }
}
