/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.category;

import java.util.Date;

import android.database.Cursor;

import ca.rmen.android.palidamuerte.provider.base.AbstractCursor;

/**
 * Cursor wrapper for the {@code category} table.
 */
public class CategoryCursor extends AbstractCursor {
    public CategoryCursor(Cursor cursor) {
        super(cursor);
    }

    /**
     * Get the {@code category_name} value.
     * Cannot be {@code null}.
     */
    public String getCategoryName() {
        Integer index = getCachedColumnIndexOrThrow(CategoryColumns.CATEGORY_NAME);
        return getString(index);
    }
}
