/*
 * This file was generated by the Android ContentProvider Generator: https://github.com/BoD/android-contentprovider-generator
 */
package ca.rmen.android.palidamuerte.provider.category;

import android.net.Uri;
import android.provider.BaseColumns;

import ca.rmen.android.palidamuerte.provider.PalidaMuerteProvider;

/**
 * Columns for the {@code category} table.
 */
public interface CategoryColumns extends BaseColumns {
    String TABLE_NAME = "category";
    Uri CONTENT_URI = Uri.parse(PalidaMuerteProvider.CONTENT_URI_BASE + "/" + TABLE_NAME);

    String _ID = BaseColumns._ID;
    String CATEGORY_NAME = "category_name";

    String DEFAULT_ORDER = _ID;

	// @formatter:off
    String[] FULL_PROJECTION = new String[] {
            _ID,
            CATEGORY_NAME
    };
    // @formatter:on
}